App\Entity\User:
  exclusion_policy: ALL
#  exclude: true
  properties:
    id:
      type: integer
      expose: true
#      serialized_name: id
      groups: ["list", "detail"]
    username:
      type: string
      expose: true
      groups: ["list", "detail"]
    password:
      type: string
      exclude: true
    isActive:
      type: boolean
      expose: true
      groups: ["list", "detail"]
    salt:
      type: string
      exclude: true
