# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
#fos_rest: ~
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
#    format_listener:
#        rules:
#            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
fos_rest:
  param_fetcher_listener:  true
  allowed_methods_listener:  true
  routing_loader: true
  format_listener:
    enabled: true
    rules:
    - { path: '^/api', priorities: ['json'], fallback_format: json }
    - { path: '^/login_check', priorities: ['json'], fallback_format: json }
    - { path: '^/', priorities: ['html'], fallback_format: html }
  body_listener:
    decoders:
      json: fos_rest.decoder.json
    array_normalizer:
      service: fos_rest.normalizer.camel_keys
      forms: true
  view:
    view_response_listener: force
    formats:
      xml: false
      json: true
  service:
    serializer: "fos_rest.serializer.symfony"
  versioning:
    enabled: true
    guessing_order:
      - query
      - custom_header
      - media_type
    resolvers:
      query: true # Query parameter: /users?version=v1
      custom_header: true # X-Accept-Version header
      media_type: # Accept header
        enabled: true
        regex: '/(v|version)=(?P<version>[0-9\.]+)/'